package dev.hycompanion.plugin.config;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import dev.hycompanion.plugin.core.npc.NpcData;
import dev.hycompanion.plugin.utils.PluginLogger;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.time.Instant;
import java.util.Map;
import java.util.Optional;
import java.util.concurrent.ConcurrentHashMap;
import java.util.stream.Stream;

/**
 * NPC配置管理器 - 管理本地缓存的NPC配置文件
 *
 * NPC数据从后端同步后以JSON5格式存储在本地磁盘。
 * 这些文件同时作为缓存和离线参考使用。
 */
public class NpcConfigManager {

    /** NPC缓存文件的存储目录 */
    private final Path cacheDirectory;
    private final PluginLogger logger;
    /** Gson实例，配置了美化输出、Instant类型适配器等 */
    private final Gson gson;

    /** NPC数据的内存缓存，键为NPC的外部ID */
    private final Map<String, NpcData> npcCache = new ConcurrentHashMap<>();

    /**
     * 构造NPC配置管理器
     *
     * @param cacheDirectory NPC缓存文件目录
     * @param logger         插件日志器
     */
    public NpcConfigManager(Path cacheDirectory, PluginLogger logger) {
        this.cacheDirectory = cacheDirectory;
        this.logger = logger;
        this.gson = new GsonBuilder()
                .setPrettyPrinting()
                .disableHtmlEscaping()
                .registerTypeAdapter(Instant.class, new InstantTypeAdapter())
                .create();

        // 如果缓存目录不存在则创建
        try {
            Files.createDirectories(cacheDirectory);
        } catch (IOException e) {
            logger.error("Failed to create NPC cache directory", e);
        }
    }

    /**
     * 从磁盘加载所有缓存的NPC配置文件
     * 扫描缓存目录下的 .json 和 .json5 文件并逐个加载
     */
    public void loadAll() {
        try (Stream<Path> files = Files.list(cacheDirectory)) {
            files.filter(p -> p.toString().endsWith(".json") || p.toString().endsWith(".json5"))
                    .forEach(this::loadNpcFile);

            logger.info("Loaded " + npcCache.size() + " cached NPCs from disk");
        } catch (IOException e) {
            logger.error("Failed to load NPC cache", e);
        }
    }

    /**
     * 将所有内存中的NPC数据保存到磁盘
     */
    public void saveAll() {
        npcCache.values().forEach(this::saveNpc);
        logger.debug("Saved " + npcCache.size() + " NPCs to cache");
    }

    /**
     * 根据外部ID获取NPC数据
     *
     * @param externalId NPC的外部唯一标识符
     * @return 包含NPC数据的Optional，不存在时为空
     */
    public Optional<NpcData> getNpc(String externalId) {
        return Optional.ofNullable(npcCache.get(externalId));
    }

    /**
     * 获取所有缓存的NPC数据（返回不可变副本）
     */
    public Map<String, NpcData> getAllNpcs() {
        return Map.copyOf(npcCache);
    }

    /**
     * 新增或更新NPC数据（从后端同步时调用）
     * 更新同步时间戳，写入内存缓存并持久化到磁盘
     */
    public void upsertNpc(NpcData npc) {
        NpcData updatedNpc = npc.withSyncedAt(Instant.now());
        npcCache.put(npc.externalId(), updatedNpc);
        saveNpc(updatedNpc);
        logger.debug("NPC upserted: " + npc.externalId() + " (" + npc.name() + ")");
    }

    /**
     * 删除指定NPC - 同时从内存缓存和磁盘文件中移除
     */
    public void removeNpc(String externalId) {
        npcCache.remove(externalId);

        try {
            Path filePath = cacheDirectory.resolve(sanitizeFilename(externalId) + ".json5");
            Files.deleteIfExists(filePath);
            logger.debug("NPC removed: " + externalId);
        } catch (IOException e) {
            logger.error("Failed to delete NPC cache file", e);
        }
    }

    /**
     * 加载单个NPC配置文件
     * 先将JSON5转换为标准JSON（去除注释），再反序列化为NpcData对象
     */
    private void loadNpcFile(Path path) {
        try {
            String content = Files.readString(path);
            // 简单的 JSON5 转 JSON 处理（移除注释和尾随逗号）
            String json = convertJson5ToJson(content);
            NpcData npc = gson.fromJson(json, NpcData.class);

            if (npc != null && npc.externalId() != null) {
                npcCache.put(npc.externalId(), npc);
            }
        } catch (Exception e) {
            logger.warn("Failed to load NPC file: " + path.getFileName());
        }
    }

    /**
     * 将单个NPC数据保存到磁盘
     * 文件格式为JSON5，带有自动生成的头部注释
     */
    private void saveNpc(NpcData npc) {
        try {
            String filename = sanitizeFilename(npc.externalId()) + ".json5";
            Path filePath = cacheDirectory.resolve(filename);

            // 添加JSON5头部注释，标明文件为自动生成
            String header = "// " + npc.name() + "\n// This file is auto-generated by sync - DO NOT EDIT MANUALLY\n";
            String json = gson.toJson(npc);

            Files.writeString(filePath, header + json);
        } catch (IOException e) {
            logger.error("Failed to save NPC: " + npc.externalId(), e);
        }
    }

    /**
     * 将JSON5转换为标准JSON格式
     * 处理内容：移除单行注释、多行注释、尾随逗号
     */
    private String convertJson5ToJson(String json5) {
        // 移除单行注释 (// ...)
        String result = json5.replaceAll("//[^\\n]*", "");
        // 移除多行注释 (/* ... */)
        result = result.replaceAll("/\\*[^*]*\\*+(?:[^/*][^*]*\\*+)*/", "");
        // 移除 } 或 ] 前面的尾随逗号
        result = result.replaceAll(",\\s*([}\\]])", "$1");
        return result;
    }

    /**
     * 将外部ID转换为安全的文件名（只保留字母、数字、下划线和连字符）
     */
    private String sanitizeFilename(String externalId) {
        return externalId.replaceAll("[^a-zA-Z0-9_-]", "_").toLowerCase();
    }

    /**
     * Instant类型的自定义Gson适配器
     * 使用ISO-8601格式进行序列化/反序列化
     * 避免Java 25模块系统下的反射问题
     */
    private static class InstantTypeAdapter extends TypeAdapter<Instant> {
        @Override
        public void write(JsonWriter out, Instant value) throws IOException {
            if (value == null) {
                out.nullValue();
            } else {
                out.value(value.toString()); // 输出ISO-8601格式字符串
            }
        }

        @Override
        public Instant read(JsonReader in) throws IOException {
            if (in.peek() == com.google.gson.stream.JsonToken.NULL) {
                in.nextNull();
                return null;
            }
            // 从ISO-8601格式字符串解析为Instant
            String text = in.nextString();
            return Instant.parse(text);
        }
    }
}
